#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: sssd-pv
#spec:
#  capacity:
#    storage: 2Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: nfs-client
#  mountOptions:
#  - hard
#  - nfsvers=4.1
#  nfs:
#    path: /nfs/containers/srv_data/sssd
#    server: nfsserver.lab.provenzawt.dev
#    readOnly: false
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: sssd-pvc
#spec:
#  storageClassName: nfs-client
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 2Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jhub-sssd
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: sssd
  template:
    metadata:
      labels:
        app: sssd
    spec:
      containers:
      - name: jhub-user-sssd
        image: registry.lab.provenzawt.dev/forme/rockysssd:latest
        volumeMounts:
        - mountPath: /var/lib/sss
          name: var-lib-sss
        securityContext:
          #privileged: true
          #capabilities:
          #  add: ["NET_ADMIN", "NET_RAW", "SYS_RESOURCE", "SYS_RAWIO", "SYS_PTRACE"]
      volumes:
      - name: var-lib-sss
        hostPath:
          path: /tmp/sss
          type: DirectoryOrCreate
